In [1]:
import numpy as np 

### Q1. Convert the list into a NumPy array and display the array

In [6]:
my_list = [1, 2, 3, 4, 5]
array = np.array(my_list)
print('converted array using numpy : ', array)


converted array using numpy :  [1 2 3 4 5]


In [3]:
type(my_array)

numpy.ndarray

### Q2. Convert the list into a NumPy array, display the array, display the first and last index, then multiply each element by 2 and display the result

In [7]:
list2 = [1, 2, 3, 4, 5]
array2 = np.array(list2)

print("NumPy array:", array2)
print("First element:", array2[0])
print("Last element:", array2[-1])

mult_array = array2 * 2
print("Array after multiplying each element by 2:", mult_array)

NumPy array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after multiplying each element by 2: [ 2  4  6  8 10]


### Q3. Create an array of 10 zeros, 10 ones, and 10 fives

In [10]:

zeros = np.zeros(10)
ones = np.ones(10)
fives = ones*5

print("Array of 10 zeros:", zeros)
print("Array of 10 ones: ", ones)
print("Array of 10 fives:", fives)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Q4. Create a 3x3 matrix with values ranging from 2 to 10

In [13]:
matrix = np.arange(2, 11).reshape(3, 3)

print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)

3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
