# NUMPY

#### IMPORTNG 

In [1]:
!pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [2]:
import numpy as np 

#### basic 

In [6]:
list=[10,20,34,50]
arr=np.array(list)
print(arr)

[10 20 34 50]


In [10]:
a=np.array(42)
b=np.array([10,20,30])
c=np.array([[10,20],[30,40]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9], [20,30,40]]])
print("array a :\n" ,a)
print("\n")
print("array b :\n" ,b)
print("\n")
print("array c :\n" ,c)
print("\n")
print("array d :\n" ,d)
print("\n")

print("a array dimension :", a.ndim)
print("b array dimension :", b.ndim)
print("c array dimension :", c.ndim)
print("d array dimension :", d.ndim)

array a :
 42


array b :
 [10 20 30]


array c :
 [[10 20]
 [30 40]]


array d :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [20 30 40]]]


a array dimension : 0
b array dimension : 1
c array dimension : 2
d array dimension : 3


#### accessing shape 

In [12]:
a.shape

()

In [13]:
b.shape

(3,)

In [14]:
c.shape

(2, 2)

In [15]:
d.shape

(2, 2, 3)

#### MORE

In [16]:
ar=np.array([10,20,30, 40 ,50 ,60])
print(ar[1:6:2])

[20 40 60]


In [21]:
s_ar=ar[1:5]
print("default array ",ar)
print("sliced array ", s_ar)


s_ar[2]=100
print("after updation ")
print("\nsliced array \n", s_ar)
print("\ndefualt array \n")
print(ar)

default array  [ 10  20  30 100  50  60]
sliced array  [ 20  30 100  50]
after updation 

sliced array 
 [ 20  30 100  50]

defualt array 

[ 10  20  30 100  50  60]


#### COPY()

In [27]:
#the changes made to copy array by copy() doent affect the original one 

In [28]:
#the view does affect the original array 

In [30]:
ar=np.array([10,3,5,6,7])
ar2=ar.copy()
ar[0]=20
print(ar)
print(ar2)

[20  3  5  6  7]
[10  3  5  6  7]


#### ZERO()

In [31]:
#generates zero 

In [36]:
#zero dimensional 
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [37]:
#1 dimensional 
a=np.zeros((6,), dtype='int')
a

array([0, 0, 0, 0, 0, 0])

In [38]:
#2 dimensional 
a=np.zeros((6,2), dtype='int')
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

#### ONES()

In [43]:
b=np.ones((6,2), dtype='int')
b


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [44]:
b=np.ones((6,2), dtype='int')*10
b

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [52]:
c=np.ones((6,2), dtype=[('x' , 'int' ),('y','float')])
c

array([[(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)],
       [(1, 1.), (1, 1.)]], dtype=[('x', '<i4'), ('y', '<f8')])

#### EYE()

In [50]:
d=np.eye(3)
print(d)
print('\n')
e=np.eye(3,4)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [55]:
ar4=np.eye(3)
print(ar4)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### DIAG()

In [54]:
ar5=np.diag((3,4,2,6))
print(ar5)
print(ar5.ndim)
print(ar5.shape)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 2 0]
 [0 0 0 6]]
2
(4, 4)


#### WHERE()

In [5]:
#the where function is used to locate the items 

In [6]:
arr1=np.array([2,3,4,5,6,7])


#### TRANSPOSE

In [4]:
#transpose is used to permute the dimension of an array , it swaps rows and columns 

In [3]:
arr =np.array([[1,2,3], [4,5,6]])
print(arr)
np.transpose (arr)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

#### SEARCHSORTED()

In [12]:
arr1=np.array([2,3,4,5,6,7])
index =np.searchsorted(arr1 , 5)
print(index)

3
